sk/recipe/urls.py
from django.urls import path
from . import views


app_name= "recipe"

urlpatterns= [
    path('home/', views.home, name="home"),
    path('add/', views.add_recipe, name="add-recipe"),
    path('details/<int:id>/', views.details, name="details"),
    path('remove/<int:id>/', views.remove_recipe, name="remove-recipe"),
    path('update/<int:id>/', views.update_recipe, name="update-recipe"),
    path('search/', views.search_recipe, name="search-recipe")
]

sk/sk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('recipe/',include('recipe.urls')),
    path('macros/',include('macros.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sk/user/urls.py
from django.urls import path
from . import views 


app_name= "user"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register , name="register"),
    path('login_user/', views.login_user, name="login"),
    path('logout_user/', views.logout_user, name="logout"),
    path('profile_list/', views.profile_list, name="profile-list"),
    path('profile/<int:id>/', views.profile , name="profile"),
    path('search_profile/', views.search_profile, name="search-profile")
]

sk/recipe/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255, null=True, blank=True)
    calories = models.FloatField(validators= [MinValueValidator(0)], default=0)
    protein = models.FloatField(validators= [MinValueValidator(0)], default=0)
    carbs = models.FloatField(validators= [MinValueValidator(0)], default=0)
    fats = models.FloatField(validators= [MinValueValidator(0)], default=0)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'brand'], name='unique_ingredient')
        ]

    def __str__(self):
        return f'{self.name} ({self.brand})' if self.brand else self.name

class Recipe(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE , default=1)
    name = models.CharField(max_length=255)
    time_to_cook = models.IntegerField(validators=[MinValueValidator(0)])
    description = models.TextField()
    image = models.ImageField(upload_to="recipe/static/images/recipes/%Y/%m/%d/", blank=True, null=True, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='recipes')
    ingredients = models.ManyToManyField('Ingredient', related_name='recipes', through='RecipeIngredient')

    def __str__(self):
        return f'{self.name}(#{self.id})'

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(default=0, validators=[MinValueValidator(0)])
    unit = models.CharField(max_length=4, default='g')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['recipe', 'ingredient'], name='unique_recipe_ingredient')
        ]

    def __str__(self):
        return f'{self.ingredient.name} - {self.recipe.name} - {self.quantity}{self.unit}'

sk/recipe/forms.py
from django import forms
from .models import Recipe, Ingredient, Category, RecipeIngredient


class RecipeIngredientForm(forms.ModelForm):
    UNIT_CHOICES = (
        ('g', 'gram'),
        ('ml', 'milliliter'),
        ('tbsp', 'tablespoon'),
        ('oz', 'ounces'),
    )

    ingredient = forms.ModelChoiceField(queryset=Ingredient.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    quantity = forms.FloatField(min_value=0, initial=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    unit = forms.ChoiceField(choices=UNIT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = RecipeIngredient
        fields = ['ingredient', 'quantity', 'unit']


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'time_to_cook', 'description', 'image', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'time_to_cook': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        recipe = super().save(commit=commit)
        return recipe

sk/recipe/views.py
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.contrib import messages
from django.urls import reverse

from macros.models import RecipeIngredientMacros, RecipeMacros
from .forms import RecipeIngredientForm, RecipeForm
from .models import Recipe, RecipeIngredient
from macros.views import calc_macros, convert2grams


# Create your views here.
def home(request):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        recipes = Recipe.objects.all
        return render(request, "recipe/home.html", {'recipes':recipes})
    

def add_recipe(request):
    if not request.user.is_authenticated:
        messages.success(request, "You need to login before accessing this page.")
        return redirect(reverse('user:login'))
    else:
        RecipeIngredientFormset = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=0)
        if request.method == 'POST':
            form = RecipeForm(request.POST, request.FILES)
            formset = RecipeIngredientFormset(request.POST, queryset=RecipeIngredient.objects.none())
            if all([form.is_valid(), formset.is_valid()]):
                recipe = form.save()
                ingredients = formset.save(commit=False)
                total_calories = 0
                total_protein = 0
                total_carbs = 0
                total_fats = 0
                for ingredient in ingredients:
                    ingredient.recipe = recipe
                    ingredient.save()
                    ingredient_macros = RecipeIngredientMacros()
                    ingredient_macros.recipe_ingredient = ingredient
                    ingredient_macros.calories = calc_macros(ingredient.ingredient.calories, convert2grams(ingredient.unit, ingredient.quantity))
                    ingredient_macros.protein = calc_macros(ingredient.ingredient.protein, convert2grams(ingredient.unit, ingredient.quantity))
                    ingredient_macros.carbs = calc_macros(ingredient.ingredient.carbs, convert2grams(ingredient.unit, ingredient.quantity))
                    ingredient_macros.fats = calc_macros(ingredient.ingredient.fats, convert2grams(ingredient.unit, ingredient.quantity))
                    ingredient_macros.save()
                    total_calories += ingredient_macros.calories
                    total_protein += ingredient_macros.protein
                    total_carbs += ingredient_macros.carbs
                    total_fats += ingredient_macros.fats
                recipe_macros = RecipeMacros()
                recipe_macros.recipe = recipe
                recipe_macros.calories = total_calories
                recipe_macros.protein = total_protein
                recipe_macros.carbs = total_carbs
                recipe_macros.fats = total_fats
                recipe_macros.save()
                return render(request, "recipe/details_recipe.html", {'recipe':recipe,'ingredients':ingredients, 'macros':recipe_macros})
        else:
            form = RecipeForm()
            formset = RecipeIngredientFormset(queryset=RecipeIngredient.objects.none())
        return render(request, 'recipe/add_recipe.html', {'form':form, 'formset': formset})


def details(request, id):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        recipe = get_object_or_404(Recipe, pk=id)
        ingredients = recipe.recipeingredient_set.all()
        return render(request, "recipe/details_recipe.html", {'recipe':recipe, 'ingredients':ingredients})


def remove_recipe(request,id):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        recipe = get_object_or_404(Recipe, pk=id)
        recipe.delete()
        messages.success(request, "Recipe Have Been Removed Successfully")
        return redirect(reverse('recipe:home'))


def update_recipe(request, id):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        recipe = get_object_or_404(Recipe, pk=id)
        RecipeIngredientFormset = modelformset_factory(
            RecipeIngredient, 
            form=RecipeIngredientForm, 
            extra=0
        )

        if request.method == 'POST':
            form = RecipeForm(request.POST, request.FILES, instance=recipe)
            formset = RecipeIngredientFormset(request.POST, queryset=recipe.recipeingredient_set.all())

            if form.is_valid() and formset.is_valid():
                recipe = form.save()
                for ingredient_form in formset:
                    if ingredient_form.is_valid():
                        ingredient = ingredient_form.save(commit=False)
                        ingredient.recipe = recipe
                        ingredient.save()

                messages.success(request, "Recipe updated successfully!")
                return redirect(reverse('recipe:details', args=[recipe.pk]))

        else:
            form = RecipeForm(instance=recipe)
            formset = RecipeIngredientFormset(queryset=recipe.recipeingredient_set.all())
            formset.prefix = 'form'

        return render(request, 'recipe/update_recipe.html', {'form': form, 'formset': formset, 'recipe': recipe})

def search_recipe(request):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        results= []
        if request.method== "POST":
            search_query = request.POST.get('search')
            recipes = Recipe.objects.all()
            for recipe in recipes:
                if search_query.lower() == recipe.name.lower():
                    results.append(recipe)
                    break
                else:
                    if search_query.lower() in recipe.name.lower():
                        results.append(recipe)

            return render(request, "recipe/search_recipe.html", {'results':results})

sk/recipe/templates/recipe/add_recipe.html
{% extends 'user/base.html' %}
{% block nav %}
{% endblock %}
{% block content %}
<style>
    .hidden {
        display: none;
    }
</style>
<form method="POST" action="{% url 'recipe:add-recipe' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{formset.management_form}}
    <div id="ingredient-form-list">
    {% for form in formset %}
    <div class="ingredient-form">
        {{form.as_p}}
    </div>
    {% endfor %}
    </div>
    <div id="empty-form" class="hidden">{{ formset.empty_form}}</div>
    <br>
    <button type="button" id="add-more">Add Ingredient</button>
    <input type="submit" value="Create Recipe">
</form>
<script>
    const addMoreBtn = document.getElementById('add-more')
    const totalNewForms = document.getElementById('id_form=TOTAL_FORMS')
    addMoreBtn.addEventListener('click',add_new_form)

    function add_new_form(event) {
    if (event) {
        event.preventDefault()
    }
    const currentIngredientForms = document.getElementsByClassName('ingredient-form')
    const currentFormCount = currentIngredientForms.length
    const formCopyTarget= document.getElementById('ingredient-form-list')
    const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
    copyEmptyFormEl.setAttribute('class','ingredient-form')
    copyEmptyFormEl.setAttribute('id',`form-${currentFormCount}`)
    const regex = new RegExp('__prefix__', 'g')
    copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
    const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
    console.log(totalNewForms)
    totalNewForms.setAttribute('value', currentFormCount + 1)
    formCopyTarget.append(copyEmptyFormEl)
}

</script>
{% endblock %}

sk/recipe/templates/recipe/home.html
{% extends "user/base.html" %}
{% block nav %}
<ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="{% url 'user:profile-list' %}">Browse Profiles</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="{% url 'user:profile' id=request.user.id %}">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" aria-current="page" href="{% url 'user:logout' %}">logout</a>
    </li>
    <form class="d-flex" role="search" method="POST" action="{% url 'recipe:search-recipe' %}" style="margin-left: 20px;">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search Recipe" aria-label="Search" name="search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</ul>
{% endblock %}
{% block content %}
<div class="container text-center">
  {% for recipe in recipes %}
  <div class="col-md-4 mb-4">
    <div class="card">
      <img src="{{recipe.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'recipe:details' recipe.id %}" style="text-decoration: none; color: black;">{{recipe.name}}</a></h5>
        <p class="card-text"><a href="{% url 'user:profile' recipe.user.id %}">Posted By: @{{recipe.user|lower}}</a></p>
      </div>
    </div>
  </div>
  <br><br><br>
  {% endfor %}
</div>
{% endblock %}