sk/recipe/urls.py
from django.urls import path
from . import views


app_name= "recipe"

urlpatterns= [
    path('home/', views.home, name="home"),
    path('add/', views.add_recipe, name="add-recipe"),
    path('details/<int:id>/', views.details, name="details"),
    path('remove/<int:id>/', views.remove_recipe, name="remove-recipe"),
    path('update/<int:id>/', views.update_recipe, name="update-recipe"),
    path('search/', views.search_recipe, name="search-recipe")
]

sk/sk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('recipe/',include('recipe.urls')),
    path('macros/',include('macros.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sk/user/urls.py
from django.urls import path
from . import views 


app_name= "user"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register , name="register"),
    path('login_user/', views.login_user, name="login"),
    path('logout_user/', views.logout_user, name="logout"),
    path('profile_list/', views.profile_list, name="profile-list"),
    path('profile/<int:id>/', views.profile , name="profile"),
    path('search_profile/', views.search_profile, name="search-profile")
]

sk/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    follow =models.ManyToManyField("self", 
            related_name="followed_by", 
            symmetrical=False,
            blank=True)
    
    date_modified= models.DateTimeField(User, auto_now=True)
    
    def __str__(self):
        return self.user.username
    
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follow.set([instance.profile.id])
        user_profile.save()
post_save.connect(create_profile, sender=User)

sk/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta: 
        model = User
        fields= ('username','first_name','last_name','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

sk/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterUserForm
from django.urls import reverse 
from .models import Profile, User
from recipe.models import Recipe

def index(request):
    return render(request, "user/about.html")

def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, (" Registration Successful! Welcome To The SocialKitchen Please Login."))
            return redirect(reverse('user:login'))
    else:
        form= RegisterUserForm()
    return render(request, 'user/register.html', {'form':form })


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username= username, password= password)
        if user is not None:
            login(request, user)
            messages.success(request, "Welcome Back!")
            return redirect(reverse('recipe:home'))
        else:
            messages.success(request, ("There Was An Error Logging In, Try Again..."))
            return redirect(reverse('user:login'))
    else: 
        return render(request, 'user/login.html', {})
    
def logout_user(request):
    logout(request)
    messages.success(request, ("You Were Logged Out! "))
    return redirect(reverse('user:index'))

def profile_list(request):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        profiles = Profile.objects.exclude(user= request.user)
        return render(request, "user/profile_list.html", {'profiles':profiles})
    
def profile(request, id):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        user = User.objects.get(id=id)
        user_profile = Profile.objects.get(user= user)
        if request.method == "POST":
            current_user_profile = request.user.profile
            action = request.POST['follow']
            if action == "unfollow":
                current_user_profile.follow.remove(user_profile)
            else:
                current_user_profile.follow.add(user_profile)
            current_user_profile.save()
        recipes = Recipe.objects.filter(user= user)
        return render(request, "user/profile.html", {'profile':user_profile, 'recipes':recipes})
    

def search_profile(request):
    if not request.user.is_authenticated:
        messages.success(request, "You Need To Login Before Accessing This Page...")
        return redirect(reverse('user:login'))
    else:
        matched_result = []
        if request.method == 'POST':
            search_query = request.POST.get('search')
            profiles = Profile.objects.exclude(user=request.user)
            for profile in profiles:
                if search_query == profile.user.username:
                    matched_result.append(profile)
                    break
                else:
                    if search_query.lower() in profile.user.username.lower():
                        matched_result.append(profile)

        return render(request, "user/search_profile.html", {'result':matched_result})

sk/user/templates/user/about.html
{% extends 'user/base.html' %}

{% block content %}
<div class="about-container">
    <header>
        <h1 class="about-heading">About SocialKitchen</h1>
    </header>
    <main>
        <section>
            <h2 class="about-subheading">Our Mission</h2>
            <p class="about-text">At SocialKitchen, we believe that cooking is for all. We encourage people to share their recipes with thousands of people and enjoy the taste of meals from all over the world. Our mission is to connect food lovers and create a community that appreciates the art of cooking.</p>
            <p class="about-text">If you have any questions or suggestions, please don't hesitate to <a href="#" class="about-link">contact us</a>.</p>
            <p>Email: &#9993; SocialKitchen@gmail.com</p>
        </section>
    </main>
    <footer>
        <p class="about-text" style="text-align: center;">&copy; 2023 SocialKitchen</p>
    </footer>
</div>

{% endblock %}

sk/user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        {% block title %}
        {% endblock %}
        <style>
          body{
            background-image: url('https://s3.envato.com/files/325634381/preview.jpg') !important;
          }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
          <div class="container-fluid">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'recipe:home' %}">Social Kitchen.</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'user:login' %}">Social Kitchen.</a>
            {% endif %}
            {% block nav %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'user:register' %}">Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'user:index' %}">About</a>
                </li>
              </ul>
            {% endblock %}
          </div>
        </nav>
          <br>
          <div class="container" style="margin-bottom: 100px;">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
          {% block content %}
          {% endblock %}
          </div>
          <div class="container-fluid">
            {% block footer %}
            {% endblock %}
          </div>
          
    </body>
</html>

sk/user/templates/user/login.html
{% extends "user/base.html" %}

{% block content %}
    <form method="POST" action="{% url 'user:login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Username</label>
            <input type="text" class="form-control" id="exampleFormControlInput1", name="username">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">password</label>
            <input type="password" class="form-control" id="exampleFormControlInput1", name="password">
        </div>
        <input type="submit" value="Login">
    </form>
{% endblock %}

sk/user/templates/user/register.html
{% extends "user/base.html" %}
{% block content %}
{% if form.errors %}
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  There was an error with your form...
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<form method="POST" action="{% url 'user:register' %}">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <input type="submit" value="Sign up">
</form>
{% endblock %}